/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vscode.java.test.sample;

import static org.mockito.Mockito.mock;
import org.junit.Test;

public class AppTest {
    @Test
    public void sampleTest() {
        ISampleService s = mock(ISampleService.class);
    }
}
